apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-user-service
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: "user-api=youngmin1085/user-service"
    argocd-image-updater.argoproj.io/user-api.update-strategy: "digest"
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: dev-project

  source:
    repoURL: https://github.com/ym1085/aws-eks-helm-lab.git
    targetRevision: dev
    path: charts/user-service
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc # 클러스터의 API 서버 주소
    namespace: dev-user-ns # 애플리케이션을 배포할 네임스페이스

  syncPolicy:
    automated: # 자동 동기화 활성화
      prune: true # Git에서 삭제된 리소스를 실제 클러스터에서도 자동 삭제할지 여부
      selfHeal: true # 클러스터 리소스가 수동으로 수정되어 Git과 달라졌을 때 자동으로 복구(동기화) 할지 여부
    syncOptions:
      - CreateNamespace=true # 네임스페이스가 없으면 자동으로 생성
      - ServerSideApply=true # 서버 사이드 적용을 사용하여 리소스를 동기화
      - ServerSideDiff=true
      - PruneLast=true
