# ArgoCD AppProject for Staging Environment
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: stg-project
  namespace: argocd
spec:
  description: "ArgoCD Staging Environment Project"

  # ArgoCD가 소스를 가져올 수 있는 저장소 지정 (Git, Helm repo 등)
  sourceRepos:
    - "https://github.com/ym1085/aws-eks-helm-lab.git"
    - "https://kubernetes.github.io/ingress-nginx"

  # ArgoCD가 배포할 수 있는 네임스페이스를 명시적으로 제한 (보안 강화)
  destinations:
    - namespace: "stg-order-ns"
      server: https://kubernetes.default.svc

    - namespace: "stg-user-ns"
      server: https://kubernetes.default.svc

    - namespace: "stg-ingress-nginx-ns"
      server: https://kubernetes.default.svc

    - namespace: "argocd"
      server: https://kubernetes.default.svc

  # ArgoCD가 모든 클러스터 리소스에 대해 CRUD 작업 수행 가능
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
