apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd
spec:
  project: prod-project

  source:
    repoURL: https://github.com/ym1085/aws-eks-helm-lab.git
    targetRevision: master
    path: charts/user-service
    helm:
      valueFiles:
        - values-prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod-user-ns

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ServerSideDiff=true
      - PruneLast=true
